seed: 1
model:
    feature_extractor:
        arch: resnet50
        pretrained: true
    classifier:
        arch: mlpcls
        nonlinear: relu
        # norm: 1 # LDAM
        feat_size: [2048, 256] # [feat_dim, bottleneck_dim]
        n_class: 31 # domainnet
data:
    source:
        loader: JSONDataLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        ann: true
        loc: false
        meta: false
    target:
        loader: JSONDataLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        ann: true
        loc: false
        meta: false
training:
    trainer: cdan
    losses:
        loss_cls:
            name: cross_entropy
        loss_d:
            name: NWDLoss
    iteration: 100004
    batch_size: 32
    # batch_size: 256
    val_interval: 5000
    save_interval: 10000
    print_interval: 2500
    optimizer:
        name: sgd
        # lr: 0.03
        momentum: 0.9
        weight_decay: 0.0005
        nesterov: true
    scheduler:
        init_lr: 0.003
        name: inv
        gamma: 0.001
        power: 0.75
    # scheduler:
    #     name: multiStepLr
    #     gamma: 0.1
    #     milestones: [35000,50000,60000]
    resume:
        model: 
        load_cls: false
        param_only: true
exp: exp
