seed: 1
model:
    feature_extractor:
        arch: resnet50
        pretrained: false
    classifier:
        arch: mlpcls
        nonlinear: relu
        feat_size: [1536, 256] 
        n_class: 24 
data:
    target:
        loader: Ego4dLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        text: false
testing:
    batch_size: 64
    resume:
        model: 
        load_cls: true
        param_only: true
exp: LagTran_video_test
