seed: 1
model:
    feature_extractor:
        arch: vitb16
        pretrained: false
    classifier:
        arch: mlpcls
        nonlinear: relu
        feat_size: [768, 256] 
        n_class: 31
data:
    target:
        loader: JSONDataLoader
        data_root: /data/
        n_workers: 4
        drop_last: true
        ann: true
        loc: false
        meta: false
testing:
    batch_size: 64
    resume:
        model: 
        load_cls: true
        param_only: true
exp: LagTran_test
